In [1]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [2]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [3]:
from __future__ import print_function
from numpy import *
from scipy import *
import matplotlib.pyplot as plt
import pickle

import matplotlib.pyplot as plt
import netCDF4 as nc
import numpy as np
import scipy as sp
import warnings
warnings.filterwarnings('ignore')

import seawater
import datetime as dt
""
from salishsea_tools import (
    nc_tools,
    viz_tools,
    geo_tools,
    tidetools
)

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
plt.style.use('seaborn-whitegrid')
import netCDF4 as nc

import cmocean as cm
import glob
import sys
sys.path.append('/data/tjarniko/mocsy')
sys.path.append('/data/tjarniko/MEOPAR/at3/notebooks/carbon_dev/CCCmaDEV/CCCma_src')
import mocsy
import CCCma
import CCCma_stations as cs
from matplotlib import reload
import arrow
import gsw
%matplotlib inline

import xarray as xr
from datetime import datetime
from salishsea_tools import grid_tools, viz_tools

from math import log10, floor


In [4]:
f = open('PI_OmA_apr_mean.pkl', 'rb')
PI_OmA_apr_mean = pickle.load(f)   
f = open('BR_OmA_apr_mean.pkl', 'rb')
BR_OmA_apr_mean = pickle.load(f)  

f = open('PI_OmA_aug_mean.pkl', 'rb')
PI_OmA_aug_mean = pickle.load(f)  
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_aug_mean = pickle.load(f)  

f = open('PI_OmA_dec_mean.pkl', 'rb')
PI_OmA_dec_mean = pickle.load(f)
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_dec_mean = pickle.load(f)

f = open('BR_T_aug_mean.pkl', 'rb')
# BR_T_aug_mean = pickle.load(f) 
# t = BR_T_aug_mean

In [5]:

f = open('PI_OmA_apr_mean.pkl', 'rb')
PI_OmA_apr_mean = pickle.load(f)   
f = open('BR_OmA_apr_mean.pkl', 'rb')
BR_OmA_apr_mean = pickle.load(f)  

f = open('PI_OmA_aug_mean.pkl', 'rb')
PI_OmA_aug_mean = pickle.load(f)  
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_aug_mean = pickle.load(f)  

f = open('PI_OmA_dec_mean.pkl', 'rb')
PI_OmA_dec_mean = pickle.load(f)
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_dec_mean = pickle.load(f)
print('benthos...')
b = 27
print('PI')
print(PI_OmA_apr_mean[b,250:252,250:252])
print('')
print(PI_OmA_aug_mean[b,250:252,250:252])
print('')
print(PI_OmA_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_OmA_apr_mean[b,250:252,250:252])
print('')
print(BR_OmA_aug_mean[b,250:252,250:252])
print('')
print(BR_OmA_dec_mean[b,250:252,250:252])
print('')

b = 28
print('below benthos...')
print('PI')
print(PI_OmA_apr_mean[b,250:252,250:252])
print('')
print(PI_OmA_aug_mean[b,250:252,250:252])
print('')
print(PI_OmA_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_OmA_apr_mean[b,250:252,250:252])
print('')
print(BR_OmA_aug_mean[b,250:252,250:252])
print('')
print(BR_OmA_dec_mean[b,250:252,250:252])
print('')

benthos...
PI
[[1.51667208 1.52062339]
 [1.51571349 1.52145277]]

[[1.19508229 1.20087725]
 [1.19421202 1.20076496]]

[[1.39048132 1.39102129]
 [1.3901835  1.3905737 ]]

BR
[[1.12643601 1.13155554]
 [1.12552179 1.13234789]]

[[1.05710249 1.05830494]
 [1.05689042 1.0576679 ]]

[[1.05710249 1.05830494]
 [1.05689042 1.0576679 ]]

below benthos...
PI
[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

BR
[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]



In [6]:
#
f = open('PI_DIC_apr_mean.pkl', 'rb')
PI_DIC_apr_mean = pickle.load(f)   
print(np.shape(PI_DIC_apr_mean))

f = open('PI_TA_apr_mean.pkl', 'rb')
PI_TA_apr_mean = pickle.load(f)  
f = open('PI_T_apr_mean.pkl', 'rb')
PI_T_apr_mean = pickle.load(f)  
f = open('PI_S_apr_mean.pkl', 'rb')
PI_S_apr_mean = pickle.load(f)  
#
f = open('BR_DIC_apr_mean.pkl', 'rb')
BR_DIC_apr_mean = pickle.load(f)   
f = open('BR_TA_apr_mean.pkl', 'rb')
BR_TA_apr_mean = pickle.load(f)  
f = open('BR_T_apr_mean.pkl', 'rb')
BR_T_apr_mean = pickle.load(f)  
f = open('BR_S_apr_mean.pkl', 'rb')
BR_S_apr_mean = pickle.load(f)  
#
f = open('PI_DIC_aug_mean.pkl', 'rb')
PI_DIC_aug_mean = pickle.load(f)   
f = open('PI_TA_aug_mean.pkl', 'rb')
PI_TA_aug_mean = pickle.load(f)  
f = open('PI_T_aug_mean.pkl', 'rb')
PI_T_aug_mean = pickle.load(f)  
f = open('PI_S_aug_mean.pkl', 'rb')
PI_S_aug_mean = pickle.load(f)  
#
f = open('BR_DIC_aug_mean.pkl', 'rb')
BR_DIC_aug_mean = pickle.load(f)   
f = open('BR_TA_aug_mean.pkl', 'rb')
BR_TA_aug_mean = pickle.load(f)  
f = open('BR_T_aug_mean.pkl', 'rb')
BR_T_aug_mean = pickle.load(f)  
f = open('BR_S_aug_mean.pkl', 'rb')
BR_S_aug_mean = pickle.load(f) 
#
f = open('PI_DIC_dec_mean.pkl', 'rb')
PI_DIC_dec_mean = pickle.load(f)   
f = open('PI_TA_dec_mean.pkl', 'rb')
PI_TA_dec_mean = pickle.load(f)  
f = open('PI_T_dec_mean.pkl', 'rb')
PI_T_dec_mean = pickle.load(f)  
f = open('PI_S_dec_mean.pkl', 'rb')
PI_S_dec_mean = pickle.load(f)  
#
f = open('BR_DIC_dec_mean.pkl', 'rb')
BR_DIC_dec_mean = pickle.load(f)   
f = open('BR_TA_dec_mean.pkl', 'rb')
BR_TA_dec_mean = pickle.load(f)  
f = open('BR_T_dec_mean.pkl', 'rb')
BR_T_dec_mean = pickle.load(f)  
f = open('BR_S_dec_mean.pkl', 'rb')
BR_S_dec_mean = pickle.load(f) 




(40, 898, 398)


In [8]:

# f = open('PI_DIC_apr_mean.pkl', 'rb')
# PI_DIC_apr_mean = pickle.load(f)   
# f = open('BR_DIC_apr_mean.pkl', 'rb')
# BR_DIC_apr_mean = pickle.load(f)  

# f = open('PI_DIC_aug_mean.pkl', 'rb')
# PI_DIC_aug_mean = pickle.load(f)  
# f = open('BR_DIC_dec_mean.pkl', 'rb')
# BR_DIC_aug_mean = pickle.load(f)  

# f = open('PI_DIC_dec_mean.pkl', 'rb')
# PI_DIC_dec_mean = pickle.load(f)
# f = open('BR_DIC_dec_mean.pkl', 'rb')
# BR_DIC_dec_mean = pickle.load(f)
print('benthos...')
b = 27
print('PI')
print(PI_DIC_apr_mean[b,250:252,250:252])
print('')
print(PI_DIC_aug_mean[b,250:252,250:252])
print('')
print(PI_DIC_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_DIC_apr_mean[b,250:252,250:252])
print('')
print(BR_DIC_aug_mean[b,250:252,250:252])
print('')
print(BR_DIC_dec_mean[b,250:252,250:252])
print('')

b = 28
print('below benthos...')
print('PI')
print(PI_DIC_apr_mean[b,250:252,250:252])
print('')
print(PI_DIC_aug_mean[b,250:252,250:252])
print('')
print(PI_DIC_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_DIC_apr_mean[b,250:252,250:252])
print('')
print(BR_DIC_aug_mean[b,250:252,250:252])
print('')
print(BR_DIC_dec_mean[b,250:252,250:252])
print('')

benthos...
PI
[[2103.62635905 2102.2203776 ]
 [2103.87186686 2101.94109701]]

[[2181.16783487 2179.49277816]
 [2181.34180475 2179.43706685]]

[[2090.28891287 2089.65692729]
 [2090.05607359 2089.50947423]]

BR
[[2152.66991374 2150.96567383]
 [2152.99234212 2150.70211589]]

[[2226.90549395 2225.22742881]
 [2226.91184948 2225.06398847]]

[[2132.12598444 2131.40012286]
 [2131.93663369 2131.29841072]]

below benthos...
PI
[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

BR
[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]



In [10]:

f = open('PI_TA_apr_mean.pkl', 'rb')
PI_TA_apr_mean = pickle.load(f)   
f = open('BR_TA_apr_mean.pkl', 'rb')
BR_TA_apr_mean = pickle.load(f)  

f = open('PI_TA_aug_mean.pkl', 'rb')
PI_TA_aug_mean = pickle.load(f)  
f = open('BR_TA_aug_mean.pkl', 'rb')
BR_TA_aug_mean = pickle.load(f)  

f = open('PI_TA_dec_mean.pkl', 'rb')
PI_TA_dec_mean = pickle.load(f)
f = open('BR_TA_dec_mean.pkl', 'rb')
BR_TA_dec_mean = pickle.load(f)
print('benthos...')
b = 27
print('PI')
print(PI_TA_apr_mean[b,250:252,250:252])
print('')
print(PI_TA_aug_mean[b,250:252,250:252])
print('')
print(PI_TA_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_TA_apr_mean[b,250:252,250:252])
print('')
print(BR_TA_aug_mean[b,250:252,250:252])
print('')
print(BR_TA_dec_mean[b,250:252,250:252])
print('')

b = 28
print('below benthos...')
print('PI')
print(PI_TA_apr_mean[b,250:252,250:252])
print('')
print(PI_TA_aug_mean[b,250:252,250:252])
print('')
print(PI_TA_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_TA_apr_mean[b,250:252,250:252])
print('')
print(BR_TA_aug_mean[b,250:252,250:252])
print('')
print(BR_TA_dec_mean[b,250:252,250:252])
print('')

benthos...
PI
[[2235.55437012 2234.62132161]
 [2235.68583171 2234.44115397]]

[[2272.23715505 2271.32205299]
 [2272.2964261  2271.25168536]]

[[2207.29277186 2206.73599735]
 [2207.02853295 2206.53712513]]

BR
[[2235.2786377  2234.28040365]
 [2235.47504069 2234.12537435]]

[[2272.02345325 2271.12833134]
 [2271.98848601 2271.00766287]]

[[2206.06394909 2205.52108272]
 [2205.85248393 2205.3370952 ]]

below benthos...
PI
[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

BR
[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]



In [11]:
def mocsy_3d_getOmA(tsal,ttemp,tdic,tta):
    tsra = np.ravel(tsal)
    ttera = np.ravel(ttemp)
    ttara = np.ravel(tta) * 1e-3
    tdra = np.ravel(tdic) * 1e-3
    tzero = np.zeros_like(tsra)
    tpressure = np.zeros_like(tsra)
    tpressure[:] =1
    tzero = tpressure * 0 

    tsra_psu = tsra*35/35.16504
    ttera_is = gsw.t_from_CT(tsra,ttera,tzero)

    response_tup = mocsy.mvars(temp=ttera_is, sal=tsra_psu, alk=ttara, dic=tdra, 
                       sil=tzero, phos=tzero, patm=tpressure, depth=tzero, lat=tzero, 
                        optcon='mol/m3', optt='Tinsitu', optp='m',
                        optb = 'l10', optk1k2='m10', optkf = 'dg', optgas = 'Pinsitu')
    pH,pco2,fco2,co2,hco3,co3,OmegaA,OmegaC,BetaD,DENis,p,Tis = response_tup


    OmegaAR = OmegaA.reshape(40,898,398)
    return OmegaAR

In [12]:
PI_OmA_apr_mean = mocsy_3d_getOmA(PI_S_apr_mean,PI_T_apr_mean,\
                                  PI_DIC_apr_mean,PI_TA_apr_mean)

BR_OmA_apr_mean = mocsy_3d_getOmA(BR_S_apr_mean,BR_T_apr_mean,\
                                  BR_DIC_apr_mean,BR_TA_apr_mean)
print('walrus')
PI_OmA_aug_mean = mocsy_3d_getOmA(PI_S_aug_mean,PI_T_aug_mean,\
                                  PI_DIC_aug_mean,PI_TA_aug_mean)
BR_OmA_aug_mean = mocsy_3d_getOmA(BR_S_aug_mean,BR_T_aug_mean,\
                                  BR_DIC_aug_mean,BR_TA_aug_mean)
PI_OmA_dec_mean = mocsy_3d_getOmA(PI_S_dec_mean,PI_T_dec_mean,\
                                  PI_DIC_dec_mean,PI_TA_dec_mean)
BR_OmA_dec_mean = mocsy_3d_getOmA(BR_S_dec_mean,BR_T_dec_mean,\
                                  BR_DIC_dec_mean,BR_TA_dec_mean)

walrus


In [13]:
print('benthos...')
b = 27
print('PI')
print(PI_OmA_apr_mean[b,250:252,250:252])
print('')
print(PI_OmA_aug_mean[b,250:252,250:252])
print('')
print(PI_OmA_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_OmA_apr_mean[b,250:252,250:252])
print('')
print(BR_OmA_aug_mean[b,250:252,250:252])
print('')
print(BR_OmA_dec_mean[b,250:252,250:252])
print('')

b = 28
print('below benthos...')
print('PI')
print(PI_OmA_apr_mean[b,250:252,250:252])
print('')
print(PI_OmA_aug_mean[b,250:252,250:252])
print('')
print(PI_OmA_dec_mean[b,250:252,250:252])
print('')
print('BR')
print(BR_OmA_apr_mean[b,250:252,250:252])
print('')
print(BR_OmA_aug_mean[b,250:252,250:252])
print('')
print(BR_OmA_dec_mean[b,250:252,250:252])
print('')

benthos...
PI
[[1.51667208 1.52062339]
 [1.51571349 1.52145277]]

[[1.19508229 1.20087725]
 [1.19421202 1.20076496]]

[[1.39048132 1.39102129]
 [1.3901835  1.3905737 ]]

BR
[[1.12643601 1.13155554]
 [1.12552179 1.13234789]]

[[0.87693993 0.8818094 ]
 [0.87667412 0.88206804]]

[[1.05710249 1.05830494]
 [1.05689042 1.0576679 ]]

below benthos...
PI
[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

BR
[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]

[[1.e+20 1.e+20]
 [1.e+20 1.e+20]]



In [17]:
mesh = xr.open_dataset('/home/sallen/MEOPAR/grid/mesh_mask201702.nc')

t = np.array(mesh.mbathy[0]) -1

print(t[250,250])
benthos_index = np.zeros([898,398])
for j in range(0,898):
    if j%50 == 0:
        print(j)
    for i in range(0,398):
        test = t[j,i]
        dat = np.where((test>0)&(test<1e19))
        W = not all(dat)

        if (W == False):#:np.isempty(dat):
            benthos = 1e20
        else:
            benthos = (np.max(dat))
        benthos_index[j,i] = (benthos)
    

27
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850


In [18]:
PI_OmA_apr_benthos = np.zeros([898,398])
BR_OmA_apr_benthos = np.zeros([898,398])
PI_OmA_aug_benthos = np.zeros([898,398])
BR_OmA_aug_benthos = np.zeros([898,398])
PI_OmA_dec_benthos = np.zeros([898,398])
BR_OmA_dec_benthos = np.zeros([898,398])

for j in range(0,898):
    if j%50 == 0:
        print(j)
    for i in range(0,398):
        benth = int(benthos_index[j,i])
        if benth > 1e10:
            PI_OmA_apr_benthos[j,i] = 1e20
            BR_OmA_apr_benthos[j,i] = 1e20
            PI_OmA_aug_benthos[j,i] = 1e20
            BR_OmA_aug_benthos[j,i] = 1e20
            PI_OmA_dec_benthos[j,i] = 1e20
            BR_OmA_dec_benthos[j,i] = 1e20      
        else:   
            PI_OmA_apr_benthos[j,i] = PI_OmA_apr_mean[benth,j,i]
            BR_OmA_apr_benthos[j,i] = BR_OmA_apr_mean[benth,j,i]
            PI_OmA_aug_benthos[j,i] = PI_OmA_aug_mean[benth,j,i]
            BR_OmA_aug_benthos[j,i] = BR_OmA_aug_mean[benth,j,i]
            PI_OmA_dec_benthos[j,i] = PI_OmA_dec_mean[benth,j,i]
            BR_OmA_dec_benthos[j,i] = BR_OmA_dec_mean[benth,j,i]

0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850


In [19]:
pickle.dump(PI_OmA_apr_benthos, open("PI_OmA_apr_benthos_mbath.pkl", 'wb'))
pickle.dump(BR_OmA_apr_benthos, open("BR_OmA_apr_benthos_mbath.pkl", 'wb'))
pickle.dump(PI_OmA_aug_benthos, open("PI_OmA_aug_benthos_mbath.pkl", 'wb'))
pickle.dump(BR_OmA_aug_benthos, open("BR_OmA_aug_benthos_mbath.pkl", 'wb'))
pickle.dump(PI_OmA_dec_benthos, open("PI_OmA_dec_benthos_mbath.pkl", 'wb'))
pickle.dump(BR_OmA_dec_benthos, open("BR_OmA_dec_benthos_mbath.pkl", 'wb'))


In [ ]:
pickle.dump(benthos_index, open("benthos_index.pkl", 'wb'))

In [ ]:
np.shape(benthos_index)

In [ ]:
#bath = nc.Dataset('/data/tjarniko/MEOPAR/grid/bathymetry_201702.nc')
#bath1 = bath.variables['Bathymetry']

def plot_bathy(surfdat_1,tit1,t_cmap,xsize,ysize,v_min1,v_max1,cl1,bigtit):

    fig, ax = plt.subplots(1, 1, figsize=(xsize, ysize), sharey=True)
    cmap = t_cmap

    tplt = np.ma.masked_values(surfdat_1,0)
    ax.set_title(tit1,fontsize = 15 )
    v_min = v_min1
    v_max = v_max1
    clabel = cl1

    viz_tools.set_aspect(ax)
    mesh = ax.pcolormesh(tplt, cmap=t_cmap, vmin=v_min, vmax=v_max) 
    ax.set_xlabel('x Index', fontsize = 20 )
    ax.set_ylabel('y Index', fontsize = 20 )

    plt.xlim([0,398])
    plt.ylim([0,898])
    plt.xticks(fontsize=8)
    plt.yticks(fontsize=8)
    cmap.set_bad('lightslategray')
    plt.suptitle(bigtit,fontsize=20)
    cbar = plt.colorbar(mesh)
    cbar.set_label(clabel)

fact = 0.19

plot_bathy(benthos_index,'Bathymetry index of the Salish Sea', \
               cm.cm.dense,20*fact,30*fact,0,40,'bathymetry (m)','')

In [ ]:
mesh = xr.open_dataset('/home/sallen/MEOPAR/grid/mesh_mask201702.nc')
mbathys = np.array(mesh.mbathy[0])

#bath = nc.Dataset('/data/tjarniko/MEOPAR/grid/bathymetry_201702.nc')
#bath1 = bath.variables['Bathymetry']

def plot_bathy(surfdat_1,tit1,t_cmap,xsize,ysize,v_min1,v_max1,cl1,bigtit):

    fig, ax = plt.subplots(1, 1, figsize=(xsize, ysize), sharey=True)
    cmap = t_cmap

    tplt = np.ma.masked_values(surfdat_1,0)
    ax.set_title(tit1,fontsize = 15 )
    v_min = v_min1
    v_max = v_max1
    clabel = cl1

    viz_tools.set_aspect(ax)
    mesh = ax.pcolormesh(tplt, cmap=t_cmap, vmin=v_min, vmax=v_max) 
    ax.set_xlabel('x Index', fontsize = 20 )
    ax.set_ylabel('y Index', fontsize = 20 )

    plt.xlim([0,398])
    plt.ylim([0,898])
    plt.xticks(fontsize=8)
    plt.yticks(fontsize=8)
    cmap.set_bad('lightslategray')
    plt.suptitle(bigtit,fontsize=20)
    cbar = plt.colorbar(mesh)
    cbar.set_label(clabel)

fact = 0.19

plot_bathy(benthos_index-(mbathys-1),'Bathymetry index of the Salish Sea', \
               cm.cm.balance,20*fact,30*fact,-3,3,'bathymetry (m)','')

In [ ]:
w = benthos_index-(mbathys-1)
w[250,250]

In [ ]:
plot_bathy(mbathys-1,'Bathymetry index of the Salish Sea', \
               cm.cm.dense,20*fact,30*fact,0,40,'bathymetry (m)','')

In [ ]:
f = open('PI_OmA_apr_mean.pkl', 'rb')
PI_OmA_apr_mean = pickle.load(f)   
f = open('BR_OmA_apr_mean.pkl', 'rb')
BR_OmA_apr_mean = pickle.load(f)  

f = open('PI_OmA_aug_mean.pkl', 'rb')
PI_OmA_aug_mean = pickle.load(f)  
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_aug_mean = pickle.load(f)  

f = open('PI_OmA_dec_mean.pkl', 'rb')
PI_OmA_dec_mean = pickle.load(f)
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_dec_mean = pickle.load(f)

f = open('BR_T_aug_mean.pkl', 'rb')
BR_T_aug_mean = pickle.load(f) 
t = BR_T_aug_mean

benthos_index = np.zeros([898,398])
for j in range(0,898):
    if j%50 == 0:
        print(j)
    for i in range(0,398):
        test = t[:,j,i]
        dat = np.where((test>0)&(test<1e19))
        W = not all(dat)

        if (W == False):#:np.isempty(dat):
            benthos = 1e20
        else:
            benthos = (np.max(dat))
        benthos_index[j,i] = (benthos)

print(PI_OmA_apr_mean[0,0,0])
PI_OmA_apr_benthos = np.zeros([898,398])
BR_OmA_apr_benthos = np.zeros([898,398])
PI_OmA_aug_benthos = np.zeros([898,398])
BR_OmA_aug_benthos = np.zeros([898,398])
PI_OmA_dec_benthos = np.zeros([898,398])
BR_OmA_dec_benthos = np.zeros([898,398])

for j in range(0,898):
    if j%50 == 0:
        print(j)
    for i in range(0,398):
        benth = int(benthos_index[j,i])
        if benth > 1e10:
            PI_OmA_apr_benthos[j,i] = 1e20
            BR_OmA_apr_benthos[j,i] = 1e20
            PI_OmA_aug_benthos[j,i] = 1e20
            BR_OmA_aug_benthos[j,i] = 1e20
            PI_OmA_dec_benthos[j,i] = 1e20
            BR_OmA_dec_benthos[j,i] = 1e20      
        else:   
            PI_OmA_apr_benthos[j,i] = PI_OmA_apr_mean[benth,j,i]
            BR_OmA_apr_benthos[j,i] = BR_OmA_apr_mean[benth,j,i]
            PI_OmA_aug_benthos[j,i] = PI_OmA_aug_mean[benth,j,i]
            BR_OmA_aug_benthos[j,i] = BR_OmA_aug_mean[benth,j,i]
            PI_OmA_dec_benthos[j,i] = PI_OmA_dec_mean[benth,j,i]
            BR_OmA_dec_benthos[j,i] = BR_OmA_dec_mean[benth,j,i]

In [ ]:
mbathys_cor = mbathys-1
mbathys_cor[250,250]

In [ ]:
f = open('PI_OmA_apr_mean.pkl', 'rb')
PI_OmA_apr_mean = pickle.load(f)   
f = open('BR_OmA_apr_mean.pkl', 'rb')
BR_OmA_apr_mean = pickle.load(f)  

f = open('PI_OmA_aug_mean.pkl', 'rb')
PI_OmA_aug_mean = pickle.load(f)  
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_aug_mean = pickle.load(f)  

f = open('PI_OmA_dec_mean.pkl', 'rb')
PI_OmA_dec_mean = pickle.load(f)
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_dec_mean = pickle.load(f)

PI_OmA_apr_benthos = np.zeros([898,398])
BR_OmA_apr_benthos = np.zeros([898,398])
PI_OmA_aug_benthos = np.zeros([898,398])
BR_OmA_aug_benthos = np.zeros([898,398])
PI_OmA_dec_benthos = np.zeros([898,398])
BR_OmA_dec_benthos = np.zeros([898,398])

mbathys_cor = mbathys-1
for j in range(0,898):
    if j%50 == 0:
        print(j)
    for i in range(0,398):
        benth = int(mbathys_cor[j,i])
        if benth < 0:
            PI_OmA_apr_benthos[j,i] = 1e20
            BR_OmA_apr_benthos[j,i] = 1e20
            PI_OmA_aug_benthos[j,i] = 1e20
            BR_OmA_aug_benthos[j,i] = 1e20
            PI_OmA_dec_benthos[j,i] = 1e20
            BR_OmA_dec_benthos[j,i] = 1e20      
        else:   
            PI_OmA_apr_benthos[j,i] = PI_OmA_apr_mean[benth,j,i]
            BR_OmA_apr_benthos[j,i] = BR_OmA_apr_mean[benth,j,i]
            PI_OmA_aug_benthos[j,i] = PI_OmA_aug_mean[benth,j,i]
            BR_OmA_aug_benthos[j,i] = BR_OmA_aug_mean[benth,j,i]
            PI_OmA_dec_benthos[j,i] = PI_OmA_dec_mean[benth,j,i]
            BR_OmA_dec_benthos[j,i] = BR_OmA_dec_mean[benth,j,i]

In [ ]:
pickle.dump(PI_OmA_apr_benthos, open("PI_OmA_apr_benthos_mbath.pkl", 'wb'))
pickle.dump(BR_OmA_apr_benthos, open("BR_OmA_apr_benthos_mbath.pkl", 'wb'))
pickle.dump(PI_OmA_aug_benthos, open("PI_OmA_aug_benthos_mbath.pkl", 'wb'))
pickle.dump(BR_OmA_aug_benthos, open("BR_OmA_aug_benthos_mbath.pkl", 'wb'))
pickle.dump(PI_OmA_dec_benthos, open("PI_OmA_dec_benthos_mbath.pkl", 'wb'))
pickle.dump(BR_OmA_dec_benthos, open("BR_OmA_dec_benthos_mbath.pkl", 'wb'))


In [ ]:
import pickle
f = open('BR_OmA_aug_mean.pkl', 'rb')
BR_OmA_aug_mean = pickle.load(f) 
f = open('BR_OmA_dec_mean.pkl', 'rb')
BR_OmA_dec_mean = pickle.load(f) 

In [ ]:
BR_OmA_aug_mean[27,250:255,250:255]

In [ ]:
BR_OmA_dec_mean[27,250:255,250:255]

In [ ]:
f = open('BR_OmA_aug_benthos_mbath.pkl', 'rb')
BR_OmA_aug_benthos_mbath = pickle.load(f) 
f = open('BR_OmA_dec_benthos_mbath.pkl', 'rb')
BR_OmA_dec_benthos_mbath = pickle.load(f)

In [ ]:
BR_OmA_aug_benthos_mbath[250:255,250:255]

In [ ]:
BR_OmA_dec_benthos_mbath[250:255,250:255]